#!/usr/bin/env bash

mkdir ~/.mycoen

if [ -z "$(command -v git)" ]; then
  echo 'Git is required but not installed on your machine'
  exit 1
fi

if [ -d "$HOME/.mycoen" ]; then
  cd $HOME/.mycoen
  git pull
else
  git clone git@bitbucket.org:valentinekonov/mycoen.git $HOME/.mycoen
  cd $HOME/.mycoen
fi

if [ -z "$(grep 'source $HOME/.mycoen/.bashrc' /home/tin/.bashrc)" ]; then
  echo '# My Console Environment initial' >> $HOME/.bashrc
  echo 'source $HOME/.mycoen/.bashrc' >> $HOME/.bashrc
fi
