[ -f "$HOME/.atuin/bin/env" ] && . "$HOME/.atuin/bin/env"
[ -f "$HOME/.config/atuin/.env" ] && . "$HOME/.config/atuin/.env"

if command -v atuin &>/dev/null; then

    #export ATUIN_TIMEOUT=5000
    export ATUIN_CONFIG_DIR="$HOME/.atuin"
    export ATUIN_NOBIND="true"
    eval "$(atuin init zsh)"

    bindkey '^r' _atuin_search_widget

    zle -N _atuinr_widget_fzf _atuinr_fzf

    _atuinr_fzf() {
        atuin history list --cmd-only | fzf
    }
    bindkey '^r' _atuin_search_widget

    #https://pastebin.com/RXxU6rT4
    #bindkey '^[[A' _atuinr_widget_fzf
    #bindkey '^[OA' _atuinr_widget_fzf
fi

# Bind Ctrl-Shift-[ to page down (scroll forward)
bindkey '^[[1;6A' forward-paragraph  # Example - adjust based on what cat -v shows

# Bind Ctrl-Shift-] to page up (scroll backward)
bindkey '^[[1;6B' backward-paragraph  # Example - adjust based on what cat -v shows
